# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/neto/Projects/Topo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/neto/Projects/Topo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/neto/Projects/Topo/CMakeFiles /home/neto/Projects/Topo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/neto/Projects/Topo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named topogen

# Build rule for target.
topogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 topogen
.PHONY : topogen

# fast build rule for target.
topogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/build
.PHONY : topogen/fast

basalt.o: basalt.cpp.o
.PHONY : basalt.o

# target to build an object file
basalt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/basalt.cpp.o
.PHONY : basalt.cpp.o

basalt.i: basalt.cpp.i
.PHONY : basalt.i

# target to preprocess a source file
basalt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/basalt.cpp.i
.PHONY : basalt.cpp.i

basalt.s: basalt.cpp.s
.PHONY : basalt.s

# target to generate assembly for a file
basalt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/basalt.cpp.s
.PHONY : basalt.cpp.s

contour.o: contour.cpp.o
.PHONY : contour.o

# target to build an object file
contour.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/contour.cpp.o
.PHONY : contour.cpp.o

contour.i: contour.cpp.i
.PHONY : contour.i

# target to preprocess a source file
contour.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/contour.cpp.i
.PHONY : contour.cpp.i

contour.s: contour.cpp.s
.PHONY : contour.s

# target to generate assembly for a file
contour.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/contour.cpp.s
.PHONY : contour.cpp.s

delve_render.o: delve_render.cpp.o
.PHONY : delve_render.o

# target to build an object file
delve_render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/delve_render.cpp.o
.PHONY : delve_render.cpp.o

delve_render.i: delve_render.cpp.i
.PHONY : delve_render.i

# target to preprocess a source file
delve_render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/delve_render.cpp.i
.PHONY : delve_render.cpp.i

delve_render.s: delve_render.cpp.s
.PHONY : delve_render.s

# target to generate assembly for a file
delve_render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/delve_render.cpp.s
.PHONY : delve_render.cpp.s

detail.o: detail.cpp.o
.PHONY : detail.o

# target to build an object file
detail.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/detail.cpp.o
.PHONY : detail.cpp.o

detail.i: detail.cpp.i
.PHONY : detail.i

# target to preprocess a source file
detail.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/detail.cpp.i
.PHONY : detail.cpp.i

detail.s: detail.cpp.s
.PHONY : detail.s

# target to generate assembly for a file
detail.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/detail.cpp.s
.PHONY : detail.cpp.s

gpu.o: gpu.cpp.o
.PHONY : gpu.o

# target to build an object file
gpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/gpu.cpp.o
.PHONY : gpu.cpp.o

gpu.i: gpu.cpp.i
.PHONY : gpu.i

# target to preprocess a source file
gpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/gpu.cpp.i
.PHONY : gpu.cpp.i

gpu.s: gpu.cpp.s
.PHONY : gpu.s

# target to generate assembly for a file
gpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/gpu.cpp.s
.PHONY : gpu.cpp.s

imgui/backends/imgui_impl_sdl3.o: imgui/backends/imgui_impl_sdl3.cpp.o
.PHONY : imgui/backends/imgui_impl_sdl3.o

# target to build an object file
imgui/backends/imgui_impl_sdl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_sdl3.cpp.o
.PHONY : imgui/backends/imgui_impl_sdl3.cpp.o

imgui/backends/imgui_impl_sdl3.i: imgui/backends/imgui_impl_sdl3.cpp.i
.PHONY : imgui/backends/imgui_impl_sdl3.i

# target to preprocess a source file
imgui/backends/imgui_impl_sdl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_sdl3.cpp.i
.PHONY : imgui/backends/imgui_impl_sdl3.cpp.i

imgui/backends/imgui_impl_sdl3.s: imgui/backends/imgui_impl_sdl3.cpp.s
.PHONY : imgui/backends/imgui_impl_sdl3.s

# target to generate assembly for a file
imgui/backends/imgui_impl_sdl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_sdl3.cpp.s
.PHONY : imgui/backends/imgui_impl_sdl3.cpp.s

imgui/backends/imgui_impl_sdlgpu3.o: imgui/backends/imgui_impl_sdlgpu3.cpp.o
.PHONY : imgui/backends/imgui_impl_sdlgpu3.o

# target to build an object file
imgui/backends/imgui_impl_sdlgpu3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_sdlgpu3.cpp.o
.PHONY : imgui/backends/imgui_impl_sdlgpu3.cpp.o

imgui/backends/imgui_impl_sdlgpu3.i: imgui/backends/imgui_impl_sdlgpu3.cpp.i
.PHONY : imgui/backends/imgui_impl_sdlgpu3.i

# target to preprocess a source file
imgui/backends/imgui_impl_sdlgpu3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_sdlgpu3.cpp.i
.PHONY : imgui/backends/imgui_impl_sdlgpu3.cpp.i

imgui/backends/imgui_impl_sdlgpu3.s: imgui/backends/imgui_impl_sdlgpu3.cpp.s
.PHONY : imgui/backends/imgui_impl_sdlgpu3.s

# target to generate assembly for a file
imgui/backends/imgui_impl_sdlgpu3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_sdlgpu3.cpp.s
.PHONY : imgui/backends/imgui_impl_sdlgpu3.cpp.s

imgui/imgui.o: imgui/imgui.cpp.o
.PHONY : imgui/imgui.o

# target to build an object file
imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui.cpp.o
.PHONY : imgui/imgui.cpp.o

imgui/imgui.i: imgui/imgui.cpp.i
.PHONY : imgui/imgui.i

# target to preprocess a source file
imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui.cpp.i
.PHONY : imgui/imgui.cpp.i

imgui/imgui.s: imgui/imgui.cpp.s
.PHONY : imgui/imgui.s

# target to generate assembly for a file
imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui.cpp.s
.PHONY : imgui/imgui.cpp.s

imgui/imgui_draw.o: imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.o

# target to build an object file
imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.cpp.o

imgui/imgui_draw.i: imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.i

# target to preprocess a source file
imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.cpp.i

imgui/imgui_draw.s: imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.s

# target to generate assembly for a file
imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.cpp.s

imgui/imgui_tables.o: imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.o

# target to build an object file
imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.cpp.o

imgui/imgui_tables.i: imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.i

# target to preprocess a source file
imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.cpp.i

imgui/imgui_tables.s: imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.s

# target to generate assembly for a file
imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.cpp.s

imgui/imgui_widgets.o: imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.o

# target to build an object file
imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.cpp.o

imgui/imgui_widgets.i: imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.i

# target to preprocess a source file
imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.cpp.i

imgui/imgui_widgets.s: imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.s

# target to generate assembly for a file
imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.cpp.s

imgui_ui.o: imgui_ui.cpp.o
.PHONY : imgui_ui.o

# target to build an object file
imgui_ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/imgui_ui.cpp.o
.PHONY : imgui_ui.cpp.o

imgui_ui.i: imgui_ui.cpp.i
.PHONY : imgui_ui.i

# target to preprocess a source file
imgui_ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/imgui_ui.cpp.i
.PHONY : imgui_ui.cpp.i

imgui_ui.s: imgui_ui.cpp.s
.PHONY : imgui_ui.s

# target to generate assembly for a file
imgui_ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/imgui_ui.cpp.s
.PHONY : imgui_ui.cpp.s

isometric.o: isometric.cpp.o
.PHONY : isometric.o

# target to build an object file
isometric.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/isometric.cpp.o
.PHONY : isometric.cpp.o

isometric.i: isometric.cpp.i
.PHONY : isometric.i

# target to preprocess a source file
isometric.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/isometric.cpp.i
.PHONY : isometric.cpp.i

isometric.s: isometric.cpp.s
.PHONY : isometric.s

# target to generate assembly for a file
isometric.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/isometric.cpp.s
.PHONY : isometric.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/main.cpp.s
.PHONY : main.cpp.s

map_gen.o: map_gen.cpp.o
.PHONY : map_gen.o

# target to build an object file
map_gen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/map_gen.cpp.o
.PHONY : map_gen.cpp.o

map_gen.i: map_gen.cpp.i
.PHONY : map_gen.i

# target to preprocess a source file
map_gen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/map_gen.cpp.i
.PHONY : map_gen.cpp.i

map_gen.s: map_gen.cpp.s
.PHONY : map_gen.s

# target to generate assembly for a file
map_gen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/map_gen.cpp.s
.PHONY : map_gen.cpp.s

marble.o: marble.cpp.o
.PHONY : marble.o

# target to build an object file
marble.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/marble.cpp.o
.PHONY : marble.cpp.o

marble.i: marble.cpp.i
.PHONY : marble.i

# target to preprocess a source file
marble.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/marble.cpp.i
.PHONY : marble.cpp.i

marble.s: marble.cpp.s
.PHONY : marble.s

# target to generate assembly for a file
marble.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/marble.cpp.s
.PHONY : marble.cpp.s

noise.o: noise.cpp.o
.PHONY : noise.o

# target to build an object file
noise.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/noise.cpp.o
.PHONY : noise.cpp.o

noise.i: noise.cpp.i
.PHONY : noise.i

# target to preprocess a source file
noise.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/noise.cpp.i
.PHONY : noise.cpp.i

noise.s: noise.cpp.s
.PHONY : noise.s

# target to generate assembly for a file
noise.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/noise.cpp.s
.PHONY : noise.cpp.s

terrain_generator.o: terrain_generator.cpp.o
.PHONY : terrain_generator.o

# target to build an object file
terrain_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/terrain_generator.cpp.o
.PHONY : terrain_generator.cpp.o

terrain_generator.i: terrain_generator.cpp.i
.PHONY : terrain_generator.i

# target to preprocess a source file
terrain_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/terrain_generator.cpp.i
.PHONY : terrain_generator.cpp.i

terrain_generator.s: terrain_generator.cpp.s
.PHONY : terrain_generator.s

# target to generate assembly for a file
terrain_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/terrain_generator.cpp.s
.PHONY : terrain_generator.cpp.s

water.o: water.cpp.o
.PHONY : water.o

# target to build an object file
water.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/water.cpp.o
.PHONY : water.cpp.o

water.i: water.cpp.i
.PHONY : water.i

# target to preprocess a source file
water.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/water.cpp.i
.PHONY : water.cpp.i

water.s: water.cpp.s
.PHONY : water.s

# target to generate assembly for a file
water.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/water.cpp.s
.PHONY : water.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... imgui"
	@echo "... topogen"
	@echo "... basalt.o"
	@echo "... basalt.i"
	@echo "... basalt.s"
	@echo "... contour.o"
	@echo "... contour.i"
	@echo "... contour.s"
	@echo "... delve_render.o"
	@echo "... delve_render.i"
	@echo "... delve_render.s"
	@echo "... detail.o"
	@echo "... detail.i"
	@echo "... detail.s"
	@echo "... gpu.o"
	@echo "... gpu.i"
	@echo "... gpu.s"
	@echo "... imgui/backends/imgui_impl_sdl3.o"
	@echo "... imgui/backends/imgui_impl_sdl3.i"
	@echo "... imgui/backends/imgui_impl_sdl3.s"
	@echo "... imgui/backends/imgui_impl_sdlgpu3.o"
	@echo "... imgui/backends/imgui_impl_sdlgpu3.i"
	@echo "... imgui/backends/imgui_impl_sdlgpu3.s"
	@echo "... imgui/imgui.o"
	@echo "... imgui/imgui.i"
	@echo "... imgui/imgui.s"
	@echo "... imgui/imgui_draw.o"
	@echo "... imgui/imgui_draw.i"
	@echo "... imgui/imgui_draw.s"
	@echo "... imgui/imgui_tables.o"
	@echo "... imgui/imgui_tables.i"
	@echo "... imgui/imgui_tables.s"
	@echo "... imgui/imgui_widgets.o"
	@echo "... imgui/imgui_widgets.i"
	@echo "... imgui/imgui_widgets.s"
	@echo "... imgui_ui.o"
	@echo "... imgui_ui.i"
	@echo "... imgui_ui.s"
	@echo "... isometric.o"
	@echo "... isometric.i"
	@echo "... isometric.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... map_gen.o"
	@echo "... map_gen.i"
	@echo "... map_gen.s"
	@echo "... marble.o"
	@echo "... marble.i"
	@echo "... marble.s"
	@echo "... noise.o"
	@echo "... noise.i"
	@echo "... noise.s"
	@echo "... terrain_generator.o"
	@echo "... terrain_generator.i"
	@echo "... terrain_generator.s"
	@echo "... water.o"
	@echo "... water.i"
	@echo "... water.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

